### ISSUE TITLE
Giant undeground cims

### ISSUE THREAD

**Issue by originalfoo** [Quistar-LAB/EManagersLib#7]
So, I've recently been getting gargantuan ghost cims whenever I'm in "white map" view (info views, underground bulldozer, etc...)

![image](https://user-images.githubusercontent.com/1386719/148678446-a03a8982-f6f4-405c-8e2e-58bb830b4bc9.png)

They move around slowly and occasionally disappear. Also, if I move camera around or zoom out too much they sometimes disappear from view (returning camera to prior position makes them appear again).

<details><summary>Normal city view for comparison</summary>

![image](https://user-images.githubusercontent.com/1386719/148678489-fca6ea0b-a09d-4b83-a3ff-c15efa00cd92.png)

</details>

As far as I can tell there is one per [Underground Elevator](https://steamcommunity.com/sharedfiles/filedetails/?id=1118944957) building (I have 2 such buildings in that town currently). I've been using that workshop asset since it was released and never had gargantuan ghost cims before.

I've only ever seen this happen since using Tree / Prop Anarchy  and EManagers... Is it possible that some of  your changes to info views could be causing interdimensional mutant cims?

**Comment by originalfoo** [comment]
Getting them in landscaping view too 
![image](https://user-images.githubusercontent.com/1386719/148679274-157bf5dd-f56f-4148-a60c-65dd09ccb35a.png)

**Comment by originalfoo** [comment]
Hrm, it might be a broken cim asset... Might be one of these three...

![image](https://user-images.githubusercontent.com/1386719/148679460-6fcd37bd-6f95-4f82-8214-17cec0a3ff1a.png)

**Comment by Quistar-LAB** [comment]
I highly doubt it caused by EML. Prop Anarchy doesn't patch the game (it only patches MoveIt mod, for the prop painter function). EML patches prop framework, and other areas such as building/network framework to deal with building/network assets that contain props. As to sims... not sure why you're experiencing this, but if they got lost in that underground tunnel, I think you'd have a better chance at finding the issue if you look towards pathfinding. Sims aren't a part of the prop framework.

As to the infoview. Prop framework has no info view. Trees do have them, but I doubt my adjustment to the tree framework is affecting cims all of a sudden, plus they're focused towards natural resources, and fire risk info views
